# Generated by Django 4.1.2 on 2023-03-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
