# Generated by Django 4.1.2 on 2023-03-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_city_order_pin_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pin',
        ),
    ]
