# Generated by Django 4.1.2 on 2023-04-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(blank=True, max_length=50, null=True)),
                ('Cemail', models.EmailField(max_length=254)),
                ('Cmsg', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
