# Generated by Django 4.1.2 on 2023-04-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_payment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='CardMonth',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='CardYear',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
