# Generated by Django 4.1.2 on 2023-04-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_payment_cardmonth_payment_cardyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='CardNo',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
    ]
