# Generated by Django 4.1.2 on 2023-04-30 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='CardMonth',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='CardYear',
        ),
        migrations.AlterField(
            model_name='payment',
            name='CardCvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,3}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='CardNo',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,16}$')]),
        ),
    ]
