# Generated by Django 4.1.2 on 2023-04-30 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_payment_cardmonth_remove_payment_cardyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='CardCvv',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,3}$')]),
        ),
    ]
