# Generated by Django 4.1.2 on 2023-04-30 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_payment_cardcvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='CardMonth',
            field=models.CharField(max_length=2, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,2}$')]),
        ),
        migrations.AddField(
            model_name='payment',
            name='CardYear',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,4}$')]),
        ),
    ]
