# Generated by Django 4.1.2 on 2023-04-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_payment_cardmonth_payment_cardyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='queNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
