# Generated by Django 4.1.2 on 2023-05-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupProducts',
            new_name='SupProduct',
        ),
    ]
