# Generated by Django 4.1.2 on 2023-05-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_supproducts_supproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='CouponName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='ans',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='que',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='queNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Cmsg',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Cname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SupAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supproduct',
            name='SupDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='supproduct',
            name='SupQuantity',
            field=models.IntegerField(null=True),
        ),
    ]
