# Generated by Django 4.1.2 on 2023-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_coupon_couponname_alter_faq_ans_alter_faq_que_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='CouponDis',
            field=models.IntegerField(null=True),
        ),
    ]
