# Generated by Django 4.1.2 on 2023-05-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
