# Generated by Django 4.1.2 on 2023-05-03 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
