# Generated by Django 4.1.2 on 2023-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisName', models.CharField(max_length=50, null=True)),
                ('DisPer', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
