# Generated by Django 4.1.2 on 2023-05-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_discount_delete_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Cname',
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
