# Generated by Django 4.1.2 on 2023-05-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_review_cname_review_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.AddField(
            model_name='review',
            name='Cname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
